# Generated by Django 4.1.3 on 2022-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="date_creation",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="date_modification",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
