# Generated by Django 4.1.3 on 2022-11-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPlus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
    ]
