# Generated by Django 4.1.3 on 2022-11-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_alter_utilisateur_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
