# Generated by Django 4.1.3 on 2022-11-30 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_utilisateur_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
